name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Construct Docker Tag
      id: docker_tag
      run: |
        REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        TIMESTAMP=$(date +%s)
        DOCKER_TAG="${{ secrets.DOCKERHUB_USERNAME }}/${REPO_NAME}:${{ github.run_number }}-$TIMESTAMP"
        echo "Constructed Docker Tag: $DOCKER_TAG"
        echo "DOCKER_TAG=$DOCKER_TAG" >> $GITHUB_ENV
        echo "::set-output name=tag::$DOCKER_TAG"

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.docker_tag.outputs.tag }}
