name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Get current timestamp
      id: timestamp
      run: echo "::set-output name=timestamp::$(date +%s)"

    - name: Prepare Docker Tag
      id: prep
      run: |
        echo "::set-output name=tag::${{ secrets.DOCKERHUB_USERNAME }}/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]'):${{ github.run_number }}-${{ steps.timestamp.outputs.timestamp }}"

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.prep.outputs.tag }}
